### ISSUE TITLE
Enable password when integrate with existing flask app.

### ISSUE THREAD

**Issue by mau21mau** [Parallels/rq-dashboard#150] opened 2018-02-23 20:13 UTC
This tool provides the ability to be integrated with an existing tool, as shown at the docs.

```
app = Flask(__name__)
app.config.from_object(rq_dashboard.default_settings)
app.register_blueprint(rq_dashboard.blueprint, url_prefix="/rq")
```

Although if I use this feature the dashboard runs as public route. It would be great If it had an option to override it's authentication with our own authentication route or provide the user and password anyhow.

**Comment by eoranged** [comment] 2018-03-22 22:00
It is regular Flask blueprint, so you can use something like
```
@rq_dashboard.blueprint.before_request
def check_auth():
    if not my_auth_module.check_auth(request):
        abort(401)
```

**Comment by eoranged** [comment] 2019-05-05 20:59
Closing this. Feel free to reopen If you have any additional questions.

**Closed as completed by eoranged** 2019-05-05 20:59 UTC

**Comment by siparker** [comment] 2024-03-02 15:04
If used in an app factory approach where would you put this?
and is there some missing docs on how to utilise a normal app config. as all of this is ignored. 

    app.config['RQ_DASHBOARD_USERNAME'] = app.config.get('RQ_DASHBOARD_USERNAME', 'admin')
    app.config['RQ_DASHBOARD_PASSWORD'] = app.config.get('RQ_DASHBOARD_PASSWORD', 'admin')
    app.config['RQ_DASHBOARD_URL_PREFIX'] = '/rq-dashboard'
    app.config['BASIC_AUTH_USERNAME'] = os.getenv('RQ_DASHBOARD_USERNAME', 'admin')
    app.config['BASIC_AUTH_PASSWORD'] = os.getenv('RQ_DASHBOARD_PASSWORD', 'password')

rq_dashboard.web.setup_rq_connection(app)
just launches with default values. it doesnt use any of the config values. 
it seem the only way to actually get it to use config values is to launch from command line with the values in line. 
i assume this is not as intended but cant figure out how to utilise any of these values otherwise. 
also as the line
app.config.from_object(rq_dashboard.default_settings)
just points to a file that is only kept for historic reasons https://github.com/Parallels/rq-dashboard/blob/master/rq_dashboard/default_settings.py

is it still required. 
or is there some way that the config is meant to be loaded missing from the docs?
i would really love to use the dashboard but i have spent the last 4 hrs trying to create a way for it to work. unsuccessfully. 
end goal is i just want to have the blueprint register and then be able to have any form of access control.
ideally using my flask login manager and roles but if not then even just basic http auth is fine. but it needs something
