### ISSUE TITLE
Flask integration

### ISSUE THREAD

**Issue by jredd** [Parallels/rq-dashboard#88] opened 2015-08-26 18:56 UTC
the given example, when doing

app.config.from_object(rq_dashboard.default_settings)
app.register_blueprint(rq_dashboard.blueprint)

I receive attribute errors

Traceback (most recent call last):
  File "/my/dev/envi/path/controller_service.py", line 49, in <module>
    app.config.from_object(rq_dashboard.default_settings)
AttributeError: 'module' object has no attribute 'default_settings'

**Comment by adambyrtek** [comment] 2015-09-06 14:12
Pull request #89 should solve you problem. Let me know if it doesn't.

**Comment by eoranged** [comment] 2016-12-01 12:11
@jredd could you tell If the issue is fixed for you?

**Comment by eoranged** [comment] 2018-02-01 21:57
Looks like It is fixed, so closing. Feel free to reopen If you still facing this issue with newer versions of rq-dashboard.

**Closed as completed by eoranged** 2018-02-01 21:57 UTC
