### ISSUE TITLE
Jobs list is empty but Worker is working

### ISSUE THREAD

**Issue by ivnminin** [Parallels/rq-dashboard#169] opened 2019-01-14 14:32 UTC
That all right. sorry. need was read documents

**Comment by eoranged** [comment] 2019-05-05 20:36
Seems to be resolved.
@ivngithub please provide any additional info, so we can improve docs and/or adjust default behavior.
Closing for now. Feel free to reopen providing additional details If issue persists

**Closed as completed by eoranged** 2019-05-05 20:36 UTC

**Comment by Ambro17** [comment] 2021-08-08 14:22
Hello, sorry to revive a closed issue but i'm facing a similar issue. I'm using the default queue and the failed queue. The worker changes its icon and has the correct job details. Job is executed correctly as i can see the result via my view that fetches by task id.
The only thing that is not working is the *job count on the default queue and the list of jobs on the lower part of the page*

Should i create a minimal reproduction case? Any idea on how i may try to fix the issue?

**Comment by Ambro17** [comment] 2021-08-08 15:22
It was a human error. The job queue only shows *queued* jobs. If you only have *1* job and *1* worker it is processed immediately and it's never shown as queued.

Solution? Run a task many times, at least `number_of_workers + 1` times and with a task duration greater than 5 seconds to check if the problem is the same i had
